[tool.poetry]
name = "xdsl"
version = "0.5.0"
description = "xDSL package"
authors = ["Mathieu Fehr <mathieu.fehr@gmail.com>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.10"
lit = "^14.0.3"
yapf = ""
pytest = "&7.1.2"
filecheck = "^0.0.22"
frozenlist = "&1.3.0"
toml = "^0.10.2"
python-lsp-server = "^1.4.1"

[tool.poetry.dev-dependencies]



[build-system]
requires = [
	"poetry-core>=1.0.0",
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"
#build-backend = "poetry.core.masonry.api"

[tool.pyright]
reportImportCycles = false
reportUnnecessaryIsInstance = false
